name: stacked_cli
description: A command line tool to specially use with Flutter stacked architecture or MVVM architecture as suggested by FilledStack.
version: 1.0.9
homepage: https://github.com/Huzaifaahmed20/stacked_cli
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  process_run: ^0.10.12+1

dev_dependencies:
  pedantic: ^1.8.0

executables:
  st_cli: main
