name: stacked_cli
description: A Command Line Tool for Flutter Projects. 
version: 1.0.0
homepage: https://github.com/Huzaifaahmed20/stacked_cli
author: Huzaifa Ahmed
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0